global:
  scrape_interval: 15s  # How frequently to scrape targets by default
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'manuscript-formatter-backend'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000'] # Assuming backend runs on 8000 locally
        labels:
          environment: 'dev'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
